import type { Metadata } from 'next'
import './globals.css'
import Navbar from '../components/Navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-tl from-blue-500 via-sky-600 to-blue-900">
        
        <Navbar/>

        <main className='relative overflow-hidden'>
          {children}
        </main>

      </body>
    </html>
  )
}
